# Server Port Configuration
server.port=8080

# Logging Levels
logging.level.org.springframework.web=INFO
logging.level.com.neerveda=DEBUG

# Spring Boot Configuration
spring.main.banner-mode=console
spring.jackson.serialization.write-dates-as-timestamps=false
